# Form implementation generated from reading ui file 'c:\Users\aleva\OneDrive - Instituto Politecnico Nacional\Desktop\Documentos\PA_team\Practica7\chat.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Chat(object):
    def setupUi(self, Chat):
        Chat.setObjectName("Chat")
        Chat.resize(1036, 557)
        Chat.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(125, 154, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=Chat)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 151, 51))
        self.label_2.setStyleSheet("border-image: url(:/cct/Practica7/2015_MSN_logo.svg.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\aleva\\OneDrive - Instituto Politecnico Nacional\\Desktop\\Documentos\\PA_team\\Practica7\\../../PRACTICA7 MESSENGER/2015_MSN_logo.svg.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(830, 60, 131, 41))
        self.label_3.setStyleSheet("\n"
"font: 18pt \"MV Boli\";")
        self.label_3.setObjectName("label_3")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(740, 130, 256, 171))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 40, 131, 41))
        self.label_4.setStyleSheet("\n"
"font: 18pt \"MV Boli\";")
        self.label_4.setObjectName("label_4")
        self.img_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.img_lbl.setGeometry(QtCore.QRect(770, 330, 191, 151))
        self.img_lbl.setText("")
        self.img_lbl.setObjectName("img_lbl")
        self.Enviar_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Enviar_btn.setGeometry(QtCore.QRect(580, 350, 81, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Enviar_btn.sizePolicy().hasHeightForWidth())
        self.Enviar_btn.setSizePolicy(sizePolicy)
        self.Enviar_btn.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.Enviar_btn.setObjectName("Enviar_btn")
        self.Insertar_Texto1 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Insertar_Texto1.setGeometry(QtCore.QRect(40, 350, 531, 101))
        self.Insertar_Texto1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.SizeVerCursor))
        self.Insertar_Texto1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Insertar_Texto1.setObjectName("Insertar_Texto1")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 110, 531, 221))
        self.plainTextEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.plainTextEdit.setObjectName("plainTextEdit")
        Chat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Chat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 22))
        self.menubar.setObjectName("menubar")
        Chat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Chat)
        self.statusbar.setObjectName("statusbar")
        Chat.setStatusBar(self.statusbar)

        self.retranslateUi(Chat)
        QtCore.QMetaObject.connectSlotsByName(Chat)

    def retranslateUi(self, Chat):
        _translate = QtCore.QCoreApplication.translate
        Chat.setWindowTitle(_translate("Chat", "MainWindow"))
        self.label_3.setText(_translate("Chat", "Chat"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Chat", "Prueba"))
        item = self.listWidget.item(1)
        item.setText(_translate("Chat", "Prueba2"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("Chat", "..."))
        self.Enviar_btn.setText(_translate("Chat", "ENVIAR"))
        self.Insertar_Texto1.setHtml(_translate("Chat", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
