# Form implementation generated from reading ui file 'c:\Users\sergi\OneDrive\Documentos\UPIITA\4 Semestre\Programacion Avanzada\Practica7\Registro.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registro(object):
    def setupUi(self, Registro):
        Registro.setObjectName("Registro")
        Registro.resize(458, 571)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\sergi\\OneDrive\\Documentos\\UPIITA\\4 Semestre\\Programacion Avanzada\\Practica7\\logo_msn.jpeg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Registro.setWindowIcon(icon)
        Registro.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(125, 154, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=Registro)
        self.centralwidget.setObjectName("centralwidget")
        self.ip_txe = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ip_txe.setGeometry(QtCore.QRect(130, 30, 251, 31))
        self.ip_txe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ip_txe.setObjectName("ip_txe")
        self.port_txe = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.port_txe.setGeometry(QtCore.QRect(130, 80, 251, 31))
        self.port_txe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.port_txe.setObjectName("port_txe")
        self.correo_txe = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.correo_txe.setGeometry(QtCore.QRect(130, 130, 251, 31))
        self.correo_txe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.correo_txe.setObjectName("correo_txe")
        self.usue_txe = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.usue_txe.setGeometry(QtCore.QRect(130, 180, 251, 31))
        self.usue_txe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.usue_txe.setObjectName("usue_txe")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 49, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 49, 16))
        self.label_4.setObjectName("label_4")
        self.contras_txe = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.contras_txe.setGeometry(QtCore.QRect(130, 230, 251, 31))
        self.contras_txe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.contras_txe.setObjectName("contras_txe")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 240, 71, 16))
        self.label_5.setObjectName("label_5")
        self.registrar_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.registrar_btn.setGeometry(QtCore.QRect(350, 440, 91, 41))
        self.registrar_btn.setObjectName("registrar_btn")
        self.imagen_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagen_lbl.setGeometry(QtCore.QRect(80, 280, 221, 201))
        self.imagen_lbl.setText("")
        self.imagen_lbl.setScaledContents(True)
        self.imagen_lbl.setObjectName("imagen_lbl")
        self.imagen_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.imagen_btn.setGeometry(QtCore.QRect(340, 340, 101, 24))
        self.imagen_btn.setObjectName("imagen_btn")
        Registro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Registro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 22))
        self.menubar.setObjectName("menubar")
        Registro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Registro)
        self.statusbar.setObjectName("statusbar")
        Registro.setStatusBar(self.statusbar)

        self.retranslateUi(Registro)
        QtCore.QMetaObject.connectSlotsByName(Registro)

    def retranslateUi(self, Registro):
        _translate = QtCore.QCoreApplication.translate
        Registro.setWindowTitle(_translate("Registro", "Messenger"))
        self.label.setText(_translate("Registro", "IP:"))
        self.label_2.setText(_translate("Registro", "PORT:"))
        self.label_3.setText(_translate("Registro", "Correo:"))
        self.label_4.setText(_translate("Registro", "Usuario:"))
        self.label_5.setText(_translate("Registro", "Contraseña:"))
        self.registrar_btn.setText(_translate("Registro", "Registrar"))
        self.imagen_btn.setText(_translate("Registro", "Cargar imagen"))
