# Form implementation generated from reading ui file 'c:\Users\aleva\OneDrive - Instituto Politecnico Nacional\Desktop\Documentos\PA_team\Practica7\Registro.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registro(object):
    def setupUi(self, Registro):
        Registro.setObjectName("Registro")
        Registro.resize(469, 448)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\aleva\\OneDrive - Instituto Politecnico Nacional\\Desktop\\Documentos\\PA_team\\Practica7\\logo_msn.jpeg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Registro.setWindowIcon(icon)
        Registro.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(125, 154, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=Registro)
        self.centralwidget.setObjectName("centralwidget")
        self.correo_txe = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.correo_txe.setGeometry(QtCore.QRect(120, 20, 251, 31))
        self.correo_txe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.correo_txe.setObjectName("correo_txe")
        self.usue_txe = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.usue_txe.setGeometry(QtCore.QRect(120, 70, 251, 31))
        self.usue_txe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.usue_txe.setObjectName("usue_txe")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 49, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 70, 49, 16))
        self.label_4.setObjectName("label_4")
        self.contras_txe = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.contras_txe.setGeometry(QtCore.QRect(120, 120, 251, 31))
        self.contras_txe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.contras_txe.setObjectName("contras_txe")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 130, 71, 16))
        self.label_5.setObjectName("label_5")
        self.registrar_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.registrar_btn.setGeometry(QtCore.QRect(340, 330, 91, 41))
        self.registrar_btn.setObjectName("registrar_btn")
        self.imagen_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.imagen_lbl.setGeometry(QtCore.QRect(60, 180, 221, 201))
        self.imagen_lbl.setText("")
        self.imagen_lbl.setScaledContents(True)
        self.imagen_lbl.setObjectName("imagen_lbl")
        self.imagen_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.imagen_btn.setGeometry(QtCore.QRect(330, 230, 101, 24))
        self.imagen_btn.setObjectName("imagen_btn")
        Registro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Registro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 469, 22))
        self.menubar.setObjectName("menubar")
        Registro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Registro)
        self.statusbar.setObjectName("statusbar")
        Registro.setStatusBar(self.statusbar)

        self.retranslateUi(Registro)
        QtCore.QMetaObject.connectSlotsByName(Registro)

    def retranslateUi(self, Registro):
        _translate = QtCore.QCoreApplication.translate
        Registro.setWindowTitle(_translate("Registro", "Messenger"))
        self.label_3.setText(_translate("Registro", "Correo:"))
        self.label_4.setText(_translate("Registro", "Usuario:"))
        self.label_5.setText(_translate("Registro", "Contraseña:"))
        self.registrar_btn.setText(_translate("Registro", "Registrar"))
        self.imagen_btn.setText(_translate("Registro", "Cargar imagen"))
